### ISSUE TITLE
Need update for Long dark 1.97.

### ISSUE THREAD

**Issue by ValentinMel** [Xpazeman/tld-ambient-lights#6]
Hi. When i go in the building in pleasant valley, game just stop working at loading screen. Without this mod everything is fine.
I can give a screenshoot of MelonLoader 0.4.3. It give alot of red errors. Mod settings is updated up to 1.8.1. Mod is 2.5

**Comment by MikeGamerGuy** [comment]
Best thing you can do is navigate to your game directory.
C:\OneOrMoreDirectories\Steam\steamapps\common\TheLongDark\MelonLoader
In there you will find Latest.log. If that log is the session that contains the error then drag and drop it here. If it was a previous session go into the C:\Programs\Steam\steamapps\common\TheLongDark\MelonLoader\Logs directory and find the log that has the error and drag and drop here and you will end up with a log like this, but with errors. Ex log, no errors.
[MelonLoader_21-10-30_12-14-34.942.log](https://github.com/Xpazeman/tld-ambient-lights/files/7447561/MelonLoader_21-10-30_12-14-34.942.log)

**Comment by ValentinMel** [comment]
I guess this two ones. The game is working with this errors, but when i go in the house it just stop working.

[MelonLoader_21-10-28_18-50-23.566.log](https://github.com/Xpazeman/tld-ambient-lights/files/7448418/MelonLoader_21-10-28_18-50-23.566.log)
[MelonLoader_21-10-28_16-49-06.713.log](https://github.com/Xpazeman/tld-ambient-lights/files/7448421/MelonLoader_21-10-28_16-49-06.713.log)

**Comment by ValentinMel** [comment]
This one when i not using your mod. All works fine and no red errors.
[MelonLoader_21-10-30_13-43-19.877.log](https://github.com/Xpazeman/tld-ambient-lights/files/7448434/MelonLoader_21-10-30_13-43-19.877.log)

**Comment by mikeloeven** [comment]
It seems the lighting effects apply in some levels but not others. The brighter nights preset was not working or not showing any noticeable differences when I started chapter 4 Possibly related to missing config fiiles as the only info I could pull from the log was this line here 

[14:36:09.804] [Ambient_Lights] Initialized at: 20:34
[14:36:10.262] [Ambient_Lights] Loading Scene: BlackrockPrisonZone
[14:36:10.295] [Ambient_Lights] No lighting data for scene BlackrockPrisonZone found. Using game default.
[14:36:10.298] [Ambient_Lights] ERROR: Config isn't ready or not present.

**Comment by ValentinMel** [comment]
> 
> 
> Best thing you can do is navigate to your game directory. C:\OneOrMoreDirectories\Steam\steamapps\common\TheLongDark\MelonLoader In there you will find Latest.log. If that log is the session that contains the error then drag and drop it here. If it was a previous session go into the C:\Programs\Steam\steamapps\common\TheLongDark\MelonLoader\Logs directory and find the log from the session that has the error and drag and drop here and you will end up with a log like this, but with errors. Ex log, no errors. [MelonLoader_21-10-30_12-14-34.942.log](https://github.com/Xpazeman/tld-ambient-lights/files/7447561/MelonLoader_21-10-30_12-14-34.942.log)

How the work's going dude? Really want ot see a new update. I so am tired of playing on interloper without any lights at night.
