### ISSUE TITLE
Bad performance in Coastal Highway mines

### ISSUE THREAD

**Issue by gkalomiros** [Xpazeman/tld-ambient-lights#8]
The mines in and around Coastal Highway get really bad performance to the point of drastically reducing framerate.

**Comment by gkalomiros** [comment]
As of 2.8.1, I am still getting bad performance in the mine connecting Pleasant Valley and Coastal Highway. I have tried with only this mod and ModSettings installed using the default settings. Altering the settings doesn't seem to help. So far, other locations seem to be okay.

**Comment by ellisonch** [comment]
It's also particularly bad in the aurora mine in coastal highway.  The part before the elevator.

I've noticed it hitching in a few other places, but didn't write them down.

**Comment by Xpazeman** [comment]
Caves and mines will be removed from the mod and will use default lighting in the next version of the mod. Their light systems are too different from the rest of the interiors and not worth it working around them
